### ISSUE TITLE
page number does not show correctly when pdf viewer is resized

### ISSUE THREAD

**Issue by ylqiu** [pvginkel/PdfiumViewer#113] opened 2017-05-02 07:19 UTC
This issue can be reproduced in the sample application in the following steps:

1. Open a pdf, and navigate to a page, saying page 100. The page is rendered at 100th page, and 100 is displayed in the _page textbox, which is correct. 

2. change the window size (maximize window for example). Now you will see the number in the _page textbox is different from the currently rendered page in the viewer. 

I can repeat this problem in any pdf file, as long as the DisplayRectangleChanged event is fired.

Also I observed that the viewer does not stays in the same page when the viewer is resized. I hope it still stay at the same page before resize.

Can you please help to check it?

many thanks!

**Comment by ylqiu** [comment] 2017-05-02 07:39
I solved the problem by handling the SizeChanged event:

```
        private void pdfViewer1_SizeChanged(object sender, EventArgs e)
        {
            int pageNumber;
            if (int.TryParse(tbPagenumber.Text, out pageNumber))
            {
                pdfViewer1.Renderer.Page = pageNumber - 1;
            }
        }
```

**Comment by pvginkel** [comment] 2017-11-02 14:28
Thanks for the report. The problem seemed to be caused by the scrollbars not being corrected properly whenever the window size changed. This is now fixed.

**Closed by pvginkel** 2017-11-02 14:28 UTC
